### PR TITLE
monkey patch for PIL 1.1.7 for CMYK files

### PR DESCRIPTION
**Pull request by michaelmwu**
Version 1.1.7 of PIL seems to lack tobytes. I think someone messed up on the 2 to 3 conversion. Unfortunately I can't upgrade right away...

I didn't want to patch PIL globally so just doing it on the object

### CODE REVIEW

**Comment by kmike** [comment]
Hi,

This change makes sense, but I think that it is better to solve this issue without patching PIL, by introducing a new function 'image_tobytes' (or simply 'tobytes') like it is done for 'frombytes' - see the top of the file.

**Comment by michaelmwu** [comment]
since it's a method on an object, maybe we can just do logic to decide which method to call?

**Comment by kmike** [comment]
yeah, this also makes sense

**Comment by michaelmwu** [comment]
how's that?

**Comment by kmike** [comment]
:+1:

**Comment by kmike** [comment]
Could you please add yourself to AUTHORS.txt?

**Pull request merged**
